### ISSUE TITLE
Update design

### ISSUE THREAD

**Issue by heitortessaro** [transpara/documentation#34]
Update the design following this [Figma](https://www.figma.com/file/wDfIWs4OXwGs8lnAN28MFP/Transpara?type=design&node-id=99%3A263&mode=design&t=9bAf6kX5qaXFcmkt-1).

**Comment by heitortessaro** [comment]
Update the design following this [Figma](https://www.figma.com/file/wDfIWs4OXwGs8lnAN28MFP/Transpara?type=design&node-id=99%3A263&mode=design&t=9bAf6kX5qaXFcmkt-1).

**Comment by gabrielraeder** [comment]
Issue done.
